// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPtsXUCwwSFdmjLnNPWBPqule3hUGjvJA',
    appId: '1:599470893431:android:61a009c6474e2e63719972',
    messagingSenderId: '599470893431',
    projectId: 'wheel-chair-car-robot',
    storageBucket: 'wheel-chair-car-robot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqShKvOFjXRcMB_SEFw3yw7_KglAHg6_A',
    appId: '1:599470893431:ios:874251554351c29a719972',
    messagingSenderId: '599470893431',
    projectId: 'wheel-chair-car-robot',
    storageBucket: 'wheel-chair-car-robot.firebasestorage.app',
    iosBundleId: 'com.example.wheelchair',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfpcDHN2VVfcj5niswWCAGTe5isEySfCk',
    appId: '1:599470893431:web:35f83791b5e1ea41719972',
    messagingSenderId: '599470893431',
    projectId: 'wheel-chair-car-robot',
    authDomain: 'wheel-chair-car-robot.firebaseapp.com',
    storageBucket: 'wheel-chair-car-robot.firebasestorage.app',
    measurementId: 'G-2CSPGHL8DM',
  );
}
